In [1]:
import numpy as np

array_1 = np.array(     [ [1, 1], [-1,1] ]   )


W = np.array(     [ [1, 1], [-1,1] ]   )
print("\n W = \n", W)
#print()


array_2 = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )

X = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )
print("\n X = \n",X)
#print()

WX_1 = np.dot(W,X)
print("\n WX_1 = \n",WX_1)
#print()

WX_2 = np.matmul(W,X)
print("\n WX_2 = \n",WX_2)
#print()

#XW = np.matmul(X,W)
#print(XW)
#print()
# Lo anterior no funciona por lo siguiente:
#X_(2,3) por W_(2,2) = Resultado_(2,2)?
#porque el numero de columnas de X es diferente al numero de filas de W


 W = 
 [[ 1  1]
 [-1  1]]

 X = 
 [[1 5 2]
 [2 4 2]]

 WX_1 = 
 [[ 3  9  4]
 [ 1 -1  0]]

 WX_2 = 
 [[ 3  9  4]
 [ 1 -1  0]]


In [2]:
W = np.array([   [1,1,0,-1], [-1,1,2,-3], [-1,1,5,0]  ])
print(W)

print()

x = np.array([ [1,5,2,-1,0], [2,4,2,1,-1], [7,5,6,-1,1], [-8,0,4,-1,3] ])
print(x)
print()

b = np.zeros((3, 5)) # suponer todos los valores de los biases en cero
print(b)
print()

Z = np.matmul(W,x) + b
print(Z)

[[ 1  1  0 -1]
 [-1  1  2 -3]
 [-1  1  5  0]]

[[ 1  5  2 -1  0]
 [ 2  4  2  1 -1]
 [ 7  5  6 -1  1]
 [-8  0  4 -1  3]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[11.  9.  0.  1. -4.]
 [39.  9.  0.  3. -8.]
 [36. 24. 30. -3.  4.]]


In [6]:
#array_r_bad1 = array_1 * array_2
#print(array_r_bad1)

np.array([1,2,3])*np.array([1,2,3])


array([1, 4, 9])

In [7]:
print(np.array([2,4])*np.array([3,-5]))

[  6 -20]


In [8]:
np.multiply(np.array([2,4]), np.array([3,-5]))

array([  6, -20])

In [10]:
np.array([[1,2,3],[4,5,6]])*np.array([[1,2,3],[4,5,6]])


array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
np.multiply(np.array([[1,2,3],[4,5,6]]), np.array([[1,2,3],[4,5,6]]))

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
def get_output_from_MLP_input(W,x,b,activation="linear"):
  #print("W = ",end='\n')
  #print(W)
  print(f"W = \n {W} \n")
  #print()

  print("x = ",end='\n')
  print(x)
  print("b = ",end='\n')
  print(b)
  # arguments:
  # W,x and b are arrays

  # operations
  # Z = W x  +  b
  #Z = np.matmul(W,x) + b
  Z = np.dot(W,x) + b

  print("Z = ",end='\n')
  print(Z)

  if activation=="linear":
    y = Z

  if activation=="relu":
    # Ternary operator to define a relu function
    #y = Z if Z>=0 else 0
    #y = Z if Z>0 else 0
    #y = 0 if Z<0 else Z
    #y = 0 if Z<=0 else Z
    y = np.array([0 if z<=0 else z for z in Z])

  #TO-DO:
  """
  if activation=="sigmoid":
    #
  if activation=="tanh":
    #
  # Use many others
  if activation=="":
    #
  if activation=="":
    #
  ...

  """

  print("y = ",end='\n')
  print(y)

  return y

In [2]:
#####Resultado

import numpy as np

def get_output_from_MLP_input(W, x, b, activation="linear"):
    # Generate random values for W, x, and b greater than 8
    W = np.random.uniform(8, 10, size=W.shape)
    x = np.random.uniform(8, 10, size=x.shape)
    b = np.random.uniform(8, 10, size=b.shape)
    
    print(f"W = \n {W} \n")
    print("x = ",end='\n')
    print(x)
    print("b = ",end='\n')
    print(b)
    
    # Perform the operation Z = W x + b
    Z = np.dot(W, x) + b
    
    print("Z = ",end='\n')
    print(Z)
    
    if activation == "linear":
        y = Z
    elif activation == "relu":
        y = np.maximum(0, Z)  
    else:
        raise ValueError(f"Activation function '{activation}' not implemented")
    
    print("y = ",end='\n')
    print(y)
    
    return y


W = np.random.rand(3, 2)  
x = np.random.rand(2)     
b = np.random.rand(3)     

result = get_output_from_MLP_input(W, x, b, activation="relu")
print("Resultado de la operación numérica:")
print(result)


W = 
 [[8.79249798 8.02605362]
 [8.75739298 8.51560477]
 [9.28485984 8.3314862 ]] 

x = 
[8.06946434 9.08669727]
b = 
[9.82090748 9.09875745 9.58638877]
Z = 
[153.70197591 157.14495049 160.21592711]
y = 
[153.70197591 157.14495049 160.21592711]
Resultado de la operación numérica:
[153.70197591 157.14495049 160.21592711]


In [3]:
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b)
y

W = 
 [[8.37913378 9.64997859 8.37171306]
 [9.33561784 9.08049381 9.12538025]
 [9.48443014 9.02029568 8.04276767]
 [9.6289021  8.19755984 8.2970811 ]] 

x = 
[9.39540455 8.93604799 8.76778057]
b = 
[8.2065647  9.75451621 9.77006245 8.81355594]
Z = 
[246.56593115 258.61948257 250.00313762 245.28176117]
y = 
[246.56593115 258.61948257 250.00313762 245.28176117]


array([246.56593115, 258.61948257, 250.00313762, 245.28176117])

In [4]:
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b, activation="linear")
y

W = 
 [[8.73858883 9.64006486 9.91130897]
 [8.41450108 8.64884602 8.57994253]
 [9.8924178  8.75902304 9.24545712]
 [9.12513173 8.41884462 9.87048633]] 

x = 
[9.18013716 9.02318149 9.55139717]
b = 
[9.21292082 8.62985319 9.84045238 8.68554723]
Z = 
[271.08526814 245.86667329 267.99549213 262.69720623]
y = 
[271.08526814 245.86667329 267.99549213 262.69720623]


array([271.08526814, 245.86667329, 267.99549213, 262.69720623])

In [5]:
W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"relu")
y

W = 
 [[8.98893506 9.29477039 8.01496957]
 [9.90938757 8.92911297 8.46103486]
 [8.13040486 8.9667799  9.00767835]
 [8.77992007 8.98789059 8.33618988]] 

x = 
[8.471588   8.24086321 9.50457343]
b = 
[8.96407438 9.13605616 9.11013805 9.34125462]
Z = 
[237.89042686 247.0864306  237.4957251  237.02102579]
y = 
[237.89042686 247.0864306  237.4957251  237.02102579]


array([237.89042686, 247.0864306 , 237.4957251 , 237.02102579])

In [7]:
y = get_output_from_MLP_input(W, x, b, activation="linear")

W = 
 [[8.38912269 8.97027393 8.70268633]
 [8.22214592 8.95909357 8.1539433 ]
 [8.31370963 8.09939541 9.43497137]
 [9.41632296 9.16920671 8.30433854]] 

x = 
[9.86068506 8.40809929 9.48466854]
b = 
[9.63424439 9.51075561 8.61603475 8.25829315]
Z = 
[250.32179041 243.25314496 248.18300418 256.96918727]
y = 
[250.32179041 243.25314496 248.18300418 256.96918727]
