In [5]:

import keras
from keras.models import Sequential
from keras.layers import LSTM, Dense # Import LSTM and Dense from keras.layers
import numpy as np
import matplotlib.pyplot as plt

In [9]:
time_series = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15])
print("time_series:",time_series)
train_size=int(0.6*len(time_series))
train_data, test_data = time_series[:train_size],time_series[train_size:]
print("train_data:",train_data)
print("test_data:",test_data)

time_series: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
train_data: [1 2 3 4 5 6 7 8 9]
test_data: [10 11 12 13 14 15]


In [12]:
def create_dataset(data,seq_length):
    X,y=[],[]
    for i in range(len(data)-seq_length):
        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length])
    return np.array(X),np.array(y)

# Define seq_length outside the function
seq_length=4
# Indent these lines to be at the same level as the 'seq_length' assignment
X_train,y_train=create_dataset(train_data,seq_length)
X_test,y_test=create_dataset(test_data,seq_length)

print("conjunto de secuencias de entrenamineto:/n",X_train)
print("etiquetas de entrenamiento/n",X_train) # You probably meant to print y_train here
print("conjunto de secuencias de prueba/n",X_test)
print("etiquetas de prueba/n",y_test)

conjunto de secuencias de entrenamineto:/n [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
etiquetas de entrenamiento/n [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
conjunto de secuencias de prueba/n [[10 11 12 13]
 [11 12 13 14]]
etiquetas de prueba/n [14 15]


In [13]:
from re import X
#construccion del modelo
model=Sequential()
model.add(LSTM(16,input_shape=(seq_length,1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error',optimizer='adam')
model.fit(X_train,y_train,epochs=500)


/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 43.4433
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 43.0962
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 42.7513
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 42.4090
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 42.0692
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 41.7322
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 41.3979
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 41.0664
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 40.7378
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 40.4120
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 40.0890
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 39.7687
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 39.4509
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 39.1354
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 38.8220
Epoch

In [14]:
Evaluacion = model.evaluate(X_test,y_test)
print("Evaluacion:",Evaluacion)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - loss: 52.6200
Evaluacion: 52.620025634765625


In [15]:
#prediccion
print("X_test:/n",X_test)
print("y_test:/n",y_test)
y_pred=model.predict(X_test)
print("y_pred:/n",y_pred)

X_test:/n [[10 11 12 13]
 [11 12 13 14]]
y_test:/n [14 15]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
y_pred:/n [[7.269875]
 [7.257554]]
